### ISSUE TITLE
BaseInfra Stack Change Validation Strategy

### ISSUE THREAD

**Issue by chriselsen** [TAK-NZ/base-infra#16]
## Problem
BaseInfra stack is deployed via CI/CD to prod/dev-test environments with multiple dependent stacks. Certain changes (like VPC CIDR modifications) would break all dependent stacks, while others (NAT Gateway count) are safe.

### 1. Pre-Deployment Safety Checks
# Critical: Always run diff analysis
```cdk diff --context env=prod --profile prod```

# Look for BREAKING patterns:
- VPC CIDR changes (REPLACEMENT)
- Subnet deletions/replacements  
- KMS Key replacements
- ECS Cluster replacements

### 2. Change Classification

**🟢 SAFE (Auto-deployable):**
- Dashboard modifications
- Monitoring/alerting config
- Budget thresholds
- Tags and metadata

**🟡 CAUTION (Manual approval):**
- NAT Gateway count changes
- VPC Endpoint add/remove
- Security Group modifications

**🔴 DANGEROUS (Block in CI/CD):**
- VPC CIDR modifications
- Subnet CIDR changes
- KMS Key replacements
- ECS Cluster name changes

### 3. GitHub Actions Implementation
```
# .github/workflows/validate-base-infra.yml
jobs:
  validate:
    steps:
      - name: Breaking Change Detection
        run: |
          cdk diff --context env=prod > diff.txt
          if grep -E "(REPLACEMENT.*VPC|REPLACEMENT.*Subnet|REPLACEMENT.*KMS)" diff.txt; then
            echo "❌ BREAKING CHANGE DETECTED"
            exit 1
          fi
      
      - name: Manual Approval for Caution Changes
        if: contains(diff, 'NAT') || contains(diff, 'Endpoint')
        uses: trstringer/manual-approval@v1
        
  deploy-dev:
    needs: validate
    # Deploy dev-test first
    
  deploy-prod: 
    needs: deploy-dev
    # Only after dev-test succeeds
```

### 4. Export Stability Validation
```
# Validate critical exports never change
aws cloudformation describe-stacks \
  --stack-name TAK-Prod-BaseInfra \
  --query 'Stacks[0].Outputs[?ExportName!=null].[ExportName,Value]'
```

# Critical: VpcId, SubnetIds, KmsKeyArn, EcsClusterArn

### 5. Staged Deployment
1. **Dev-Test First**: Always deploy to dev-test environment first
2. **Integration Testing**: Validate dependent stacks still work
3. **Production**: Only deploy after dev-test validation passes

## Tasks
- [ ] Create `validate-deployment.sh` script with breaking change detection
- [ ] Implement GitHub Actions workflow with safety checks
- [ ] Add manual approval gates for caution-level changes
- [ ] Set up export stability monitoring
- [ ] Document rollback procedures
- [ ] Create change classification guidelines for team

## Acceptance Criteria
- [ ] CI/CD blocks any VPC/Subnet/KMS replacement changes
- [ ] Manual approval required for NAT Gateway/VPC Endpoint changes
- [ ] All changes deploy to dev-test before production
- [ ] Export values are validated for stability
- [ ] Team has clear guidelines on safe vs dangerous changes
